name: Build and deploy kafka-skeleton
on: push

env:
  BASE_IMAGE: ghcr.io/${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-test-and-publish:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set docker image variables
        run: |
          echo "TAG=$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "IMAGE=$BASE_IMAGE:$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and publish Docker image
        run: |
          docker build --pull --tag ${BASE_IMAGE}:${TAG} --tag ${BASE_IMAGE}:latest .
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
          docker push ${BASE_IMAGE}:${TAG}
          docker push ${BASE_IMAGE}:latest

      - name: Deploy to DEV
        uses: nais/deploy/actions/deploy@v1
        env:
          # Denne `NAIS_DEPLOY_APIKEY` må dere selv legge innunder "settings/secrets" på repoet dere har lagd (les: forket)
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/nais.yaml
          IMAGE: ${{ env.IMAGE }}
